"""Trying to get GIT automated push to work

Revision ID: 04030818aafc
Revises: 1fe50061985a
Create Date: 2024-10-17 19:51:04.956944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04030818aafc'
down_revision = '1fe50061985a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'worker', ['worker_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('help_ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
