"""empty message

Revision ID: 1c86b06264ef
Revises: ba1fc3115566
Create Date: 2024-07-16 16:38:06.963578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c86b06264ef'
down_revision = 'ba1fc3115566'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_capabilities', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('role_capabilities')

    # ### end Alembic commands ###
