"""empty message

Revision ID: edb85677083c
Revises: dab8dcb5c922
Create Date: 2024-07-16 19:27:53.082618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb85677083c'
down_revision = 'dab8dcb5c922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_capabilities', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('worker', schema=None) as batch_op:
        batch_op.drop_column('role_capabilities')

    # ### end Alembic commands ###
